export const EXIT_CODES = {
    SUCCESS: 0,
    UNKNOWN_ERROR: 1,

    CONFIG_ERROR: 10,
    DB_CONNECTION_ERROR: 20,

    AUTH_ERROR: 30,
    VALIDATION_ERROR: 40,

    EXTERNAL_API_ERROR: 50,
    UNHANDLED_EXCEPTION: 60
};